### ISSUE TITLE
Setup a quartz deploy

### ISSUE THREAD

**Issue by DefenderOfBasic** [DefenderOfBasic/in-good-faith-handbook#2]
should be very simple, see example here: https://github.com/DefenderOfBasic/works-in-progress/tree/main/quartz-notebook

should auto deploy so we can read it/link to different parts/have the links working

**Comment by DefenderOfBasic** [comment]
done! 🎉

**Comment by tonyaajjackson** [comment]
🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉
